# ====== Settings for DeathControl ======
# IMPORTANT: Do NOT use tabs in this file! Only use spaces!
# 
# Documentation about how to set up this configuration can be found here:
# http://dev.bukkit.org/server-mods/deathcontrol/pages/configuration/


use-bukkit-permissions: true
logging-level: 1
DeathCauses:
    VOID:
        keep-inventory: true
    PLAYER:
        keep-inventory: true
        cost: 300
        method: command
        timeout: 10
        loss-percentage: 12.5
    LAVA:
        keep-inventory: true
        whitelist:
        - valuables