name: DeathControl
main: bone008.bukkit.deathcontrol.DeathControl
version: 2.1.1
author: Bone008
description: Allows actions to be executed when players die under certain conditions.
softdepend: [Register, Vault]

commands:
    death:
        usage: |
            Use "/<command> help" for more information!
        aliases: [deathcontrol, dc]
        description: Generic command for the DeathControl plugin


permissions:
    deathcontrol.*:
        description: Gives access to all permissions.
        children:
            deathcontrol.use: true
            deathcontrol.free: true
            deathcontrol.crossworld: true
            deathcontrol.nolimits: true
            deathcontrol.info: true
            deathcontrol.admin: true
    deathcontrol.use:
        default: true
        description: Allows the general use of this plugin.
    deathcontrol.free:
        default: false
        description: Bypasses the cost for a death.
    deathcontrol.crossworld:
        default: false
        description: Bypasses the restriction for cross-world restoring.
    deathcontrol.nolimits:
        default: false
        description: Bypasses the limitation to certain worlds.
    deathcontrol.info:
        default: op
        description: Allows to use the info command.
    deathcontrol.admin:
        default: op
        description: Allows to reload the config files.
