name: DeathControl
main: bone008.bukkit.deathcontrol.DeathControl
version: 1.86
author: Bone008
description: Allows items to be kept when a player dies for specific reasons.
softdepend: [Register, Vault]

commands:
    death:
        usage: |
            /<command> help  for more information!
        aliases: [deathcontrol, dc]


permissions:
    deathcontrol.*:
        description: Gives access to all permissions.
        children:
            deathcontrol.use: true
            deathcontrol.free: true
            deathcontrol.crossworld: true
            deathcontrol.nolimits: true
            deathcontrol.info: true
            deathcontrol.admin: true
    deathcontrol.use:
        default: false
        description: Allows the general use of this plugin.
    deathcontrol.free:
        default: false
        description: Bypasses the cost for a death.
    deathcontrol.crossworld:
        default: false
        description: Bypasses the restriction for cross-world restoring.
    deathcontrol.nolimits:
        default: false
        description: Bypasses the limitation to certain worlds.
    deathcontrol.info:
        default: op
        description: Allows to use the info command.
    deathcontrol.admin:
        default: op
        description: Allows to reload the config files.